#ifndef CS2_PROJECT_INCLUDES_HPP
#define CS2_PROJECT_INCLUDES_HPP

#include <windows.h>
#include <cstdint>
#include <cstdio>
#include <deque>
#include <dxgi.h>
#include <d3d11.h>
#include <string>
#include <minhook/minhook.h>
#include "utils/xorstr.hpp"
#include "utils/padding.hpp"
#include "utils/console/console.hpp"
#include "utils/fnv1a.hpp"
#include "utils/winapi/nt.hpp"
#include "utils/winapi/winapi.hpp"
#include <imgui/imgui.h>
#include "imgui/imgui_impl_win32.h"
#include "imgui/imgui_impl_dx11.h"
#include "imgui/imgui_internal.h"
#include "utils/signature.hpp"
#include "utils/utils.hpp"
#include "sdk/math/color.hpp"
#include "sdk/math/vector.hpp"
#include "sdk/math/math.hpp"
#include "sdk/tier0/tier0.hpp"
#include "sdk/utl_ts_hash.hpp"
#include "sdk/enums.hpp"
#include "sdk/classes/user_cmd.hpp"
#include "sdk/interfaces/client.hpp"
#include "sdk/interfaces/global_vars.hpp"
#include "sdk/interfaces/engine_client.hpp"
#include "sdk/interfaces/csgo_input.hpp"
#include "sdk/interfaces/schema_system.hpp"
#include "sdk/interfaces/game_entity_system.hpp"
#include "sdk/schema/schema.hpp"
#include "utils/render/render.hpp"
#include "sdk/tier0/tier0.hpp"
#include "sdk/interfaces.hpp"
#include "sdk/classes/collision_property.hpp"
#include "sdk/classes/player.hpp"
#include "hooks/detour.hpp"
#include "globals.hpp"
#include "menu/menu.hpp"
#include "features/features.hpp"
#include "hooks/resize_buffers/resize_buffers.hpp"
#include "hooks/present/present.hpp"
#include "hooks/wndproc/wndproc.hpp"
#include "hooks/level_init/level_init.hpp"
#include "hooks/frame_stage_notify/frame_stage_notify.hpp"
#include "hooks/create_move/create_move.hpp"
#include "hooks/hooks.hpp"

#endif //CS2_PROJECT_INCLUDES_HPP